language: node_js

node_js:
    - 11
    - 12
    - 13
    - 14
    - node

script:
    - npm i
    - npx eslint index.js
    - npx eslint lib/*.js
    - npx eslint test/*.js
    - npm run coverage

after_success:
    - npm run coveralls

deploy:
    provider: npm
    email: justinpaulhammond@gmail.com
    api_key:
        secure: i4bPNC4JKvMjgbMdP13Z8lDmaVU67Mz+A3K4W/j7Z6TvbeUOQrzMfr927t3I9dzkiJNkcDMR8BedM6BHNq/bktUDcmusgsb+swh1Aj6iMA9Q2vPEH80Bnkpuox5hBHumf6sAoFNsEjwjXdczrEyCLEX0WVfjPdmUlPPS0E0Agqd4DeewIkhiku35oWvJ08OKGpoWbmkkv8XcNbOUFX1gQbbaDlPL+o/fzhHna/fR/PfeoSJItVqsKJ+Tj17o1zZmXhh2QHQey52WSXATwznN3TpxD9YukyZogUHUR0uDaDKmLNfKpJ//cIOjPUwqjcR5DAO7i0D2WOPuFuXyt9XW4zqCa4EtUZ6DIOfa29TKQ/Je2HPdyhtDVK2IjWeFQwT3CGbVCxxYxtXxr0Or2fncifkMhfRvev0e3w/KyQPzRnQsEQrPIMohpiVsQR6P2pWZo0BsLQSbpjW1S6/+UnXhdaHmNWcVCNA0HNn3PeY5xZuycY/vxRf4K6x8EqfZ9mrsBbVCE0J7BU+EFx52envSvSWe5gXXAPEXWE/YCprS0F/ojoGS9nw4MEaDAk4fjlqM9/LbvdVaItc3Q+3RABUGa0iJKYMTYOubEBSrTxGdfiCwtCJ5Kk2lS8jzaqJTjORLL9TY2LH+65HYbh5iDVJrV7mYJpK5w1uhv7C+c24D0DE=
    on:
        tags: true
        repo: Justintime50/labelary
    skip_cleanup: 'true'
